financeDatareader는 http://data.krx.co.kr 에서 KOSPI 데이터를 수집한다.

### 참고자료
https://financedata.github.io/marcap/

In [14]:
import pandas as pd
import seaborn as sns
import FinanceDataReader as fdr
fdr.__version__

'0.9.50'

# KRX 주식 종목 수집(KOSPI, KODAQ, KONEX 한꺼번에 수집)
### 컬럼정리
- Code : 종목코드
- ISU_CD : ISIN 코드(금융상품 식벽 국제 표준 코드)
- Name: 종목명
- Market : KOSPI, KODAQ, KONEX 구분값
- Dept : 소속부
- Close : 수집일 기준 종가
- ChnageCode : 등락기호, 가장 최근거래일의 가격 변동을 표시하는 코드(0, 1, 2, 3, 4, 5) ???
- ChangeRatio : 전일대비 등략률
- Open : 시가
- High : 고가
- Low : 저가
- Volume : 거래량
- Amount : 거래대금
- Marcap : 시가총액(원)
- Stocks : 상장주식수
- MarketId : 시장기호 ?

In [15]:
krx_df

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,68300,2,-500,-0.73,68800,69100,68200,12360193,846916262150,407736148165000,5969782550,STK
1,373220,KR7373220003,LG에너지솔루션,KOSPI,,540000,2,-3000,-0.55,545000,548000,540000,164545,89079956000,126360000000000,234000000,STK
2,000660,KR7000660001,SK하이닉스,KOSPI,,120100,1,100,0.08,118300,120900,118100,2375384,284120415050,87433084036500,728002365,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,796000,2,-11000,-1.36,808000,812000,792000,58069,46369683000,56654504000000,71174000,STK
4,005490,KR7005490008,POSCO홀딩스,KOSPI,,594000,1,2000,0.34,595000,614000,584000,1429396,855154522000,50235310620000,84571230,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,001525,KR7001521004,동양우,KOSPI,,5100,1,120,2.41,5100,5170,5100,379,1942940,3150428100,617731,STK
2737,318660,KR7318660008,타임기술,KONEX,일반기업부,1449,2,-30,-2.03,1390,1449,1321,134,178106,3118394349,2152101,KNX
2738,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1599,1,1,0.06,1599,1599,1599,1,1599,2526356040,1579960,KNX
2739,322190,KR7322190000,베른,KONEX,일반기업부,158,2,-6,-3.66,178,178,158,135,21384,1410181126,8925197,KNX
2740,308700,KR7308700004,테크엔,KONEX,일반기업부,221,2,-33,-12.99,292,292,221,110,25020,884000000,4000000,KNX

In [11]:
# KRX 전체상장 종목 수집
# krx_df = fdr.StockListing("KRX")

import inspect

print(inspect.getsource(fdr.StockListing))

def StockListing(market):
    '''
    read stock list of stock exchanges
    * market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
            'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
            'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
            'S&P500',
            'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP'
            'ETF/KR'
    '''
    market = market.upper()
    if market in [ 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP' ]:
        return KrxMarcapListing(market).read()
    if market in [ 'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC' ]:
        return KrxStockListing(market).read()
    if market in [ 'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE' ]:
        return NaverStockListing(market).read()
    if market in [ 'KRX-DELISTING' ]:
        return KrxDelisting(market).read()
    if market in [ 'KRX-ADMINISTRATIVE' ]:
        return KrxAdministrative(market).read()
    if market in [ 'S&P500', 'SP500']:
        return WikipediaStockListing(market).read()
    if market.startswith('ETF'):
        toks = market.split('/')
        etf, country = toks[0], toks[1]
        if country.upper() == 'KR':
            return NaverEtfListing().read()
    else:
        # 해외 ETF 지원 잠정 중단
        msg = "market='%s' is not implemented" % market
        raise NotImplementedError(msg)

In [24]:
fdr.StockListing('KOSPI')

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,68300,2,-500,-0.73,68800,69100,68200,12360193,846916262150,407736148165000,5969782550,STK
1,373220,KR7373220003,LG에너지솔루션,KOSPI,,540000,2,-3000,-0.55,545000,548000,540000,164545,89079956000,126360000000000,234000000,STK
2,000660,KR7000660001,SK하이닉스,KOSPI,,120100,1,100,0.08,118300,120900,118100,2375384,284120415050,87433084036500,728002365,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,796000,2,-11000,-1.36,808000,812000,792000,58069,46369683000,56654504000000,71174000,STK
4,005490,KR7005490008,POSCO홀딩스,KOSPI,,594000,1,2000,0.34,595000,614000,584000,1429396,855154522000,50235310620000,84571230,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,000227,KR7000222000,유유제약2우B,KOSPI,,10890,2,-110,-1.00,11230,11230,10370,2097,22539820,3545348400,325560,STK
945,014915,KR7014911002,성문전자우,KOSPI,,5710,1,10,0.18,5710,5740,5710,35,200730,3426000000,600000,STK
946,002787,KR7002782001,진흥기업2우B,KOSPI,,11220,1,180,1.63,11180,11220,10810,255,2794990,3307745760,294808,STK
947,001527,KR7001522002,동양2우B,KOSPI,,10460,1,80,0.77,10380,10470,10380,992,10350260,3227631740,308569,STK
948,001525,KR7001521004,동양우,KOSPI,,5100,1,120,2.41,5100,5170,5100,379,1942940,3150428100,617731,STK

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,105190,ACE 200,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
1,332500,ACE 200TR,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
2,448870,ACE 23-12 회사채(AA-이상)액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
3,448880,ACE 24-12 회사채(AA-이상)액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
4,461260,ACE 25-06 회사채(AA-이상)액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5859,419890,히어로즈 단기채권ESG액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5860,429870,히어로즈 리츠이지스액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5861,460270,히어로즈 미국달러SOFR금리액티브(합성),KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5862,459790,히어로즈 미국성장기업30액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5863,454780,히어로즈 종합채권(AA-이상)액티브,KOSPI,NaN,NaN,NaT,NaN,NaN,NaN,NaN